name: Deploy Full Stack to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Prepare Deployment Folder
      run: |
        mkdir deploy_build
        cp -R BACKEND/* deploy_build/
        cp -R FRONTEND/* deploy_build/
      
    - name: Sync Merged Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy_build/
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
