name: Deploy Full Stack to InfinityFree via FTP

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Prepare Deployment Folder & Cache Busting
      run: |
        mkdir deploy_build
        cp -R BACKEND/* deploy_build/
        cp -R FRONTEND/* deploy_build/
        VERSION=$(date +%s)
        find deploy_build/ -type f -name "*.html" -exec sed -i "s/?v=[0-9]*/?v=$VERSION/g" {} +

    - name: Sync Merged Files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./deploy_build/
        server-dir: /htdocs/
        exclude: |
          **/.git*
          **/.git*/**
